### PR TITLE
fixed missing session info causing 400 error on user create

### PR DESCRIPTION
**Pull request by gieskj01**
In order to use the session info - some config had to be added back in to the server.js

to test - use this branch then use insomnia to create a new user. You should get a 200 response/the user correctly generated. Prior we were creating the user, but getting 400 errors + the session wasn't working.

Future - we will need to add password checks for the other routes/pages so that the password actually does something. Will add another task.

### CODE REVIEW

**Comment by mmcelwee8002** [comment]
I get a 500 error when trying to post or get users with this branch

**Comment by gieskj01** [comment]
Ok - thanks for catching this - investigating . . .

**Comment by gieskj01** [comment]
@mmcelwee8002 I am not seeing any errors. Before you use npm start - make sure to set the sync value in server.js to "true. This will reset your tables, which is needed after this change. Please try this and let me know if you are still having trouble.

**Comment by gieskj01** [comment]
I am going to close this PR request as I have a new branch that incorporates these changes along with removing the userName info

**Pull request closed without merging**
